library/lib/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .import views

urlpatterns = [
     path('', views.index, name='index'),
     path('gallery1', views.gallery1, name='gallery1'),
     path('login', views.login, name='login'),
     path('logout', views.logout, name='logout'),
     path('dashboad', views.dashboad, name='dashboad'),

     path('sighup', views.sighup, name='sighup'),
     path('about', views.about, name='about'),

     path('register', views.register, name='register'),
     path('addbook', views.addbook, name='addbook'),
     path('addbookFunction', views.addbookFunction, name='addbookFunction'),
     path('showbook', views.showbook, name='showbook'),
     path('bookdelete/<int:id>', views.bookdelete, name='bookdelete'),
     path('bookedit1/<int:id>', views.bookedit1, name='bookedit1'),
     path('bookupdate/<int:id>', views.bookupdate, name='bookupdate'),
     path('addstudent', views.addstudent, name='addstudent'),
     path('addstudentfunction', views.addstudentfunction, name='addstudentfunction'),
     path('showstudent', views.showstudent, name='showstudent'),
     path('studentdelete/<int:id>', views.studentdelete, name='studentdelete'),
     path('studentedit/<int:id>', views.studentedit, name='studentedit'),
     path('studentupdate/<int:id>', views.studentupdate, name='studentupdate'),

     path('search', views.search, name='search'),
     path('searchbook', views.searchbook, name='searchbook'),
     path('issuebook1/<int:id>',views.issuebook1, name='issuebook1'),
     #path('issuebook_2', views.issuebook_2, name='issuebook_2'),

     path('showissueStData', views.showissueStData, name='showissueStData'),
     path('returnbook', views.returnbook, name='returnbook'),
     path('searchstudent', views.searchstudent, name='searchstudent'),
     path('returnbookFun/<int:isbn>', views.returnbookFun, name='returnbookFun'),
     path('issuebookfunction/<int:isbn>', views.issuebookfunction, name='issuebookfunction'),
     path('addbook_Return/<int:isbn>', views.addbook_Return, name='addbook_Return'),



]


urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/library/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lib.urls')),
]

library/lib/models.py
from django.db import models

# Create your models here.
class addbookF(models.Model):
    bookname = models.CharField(max_length=150)
    authorname = models.CharField(max_length=150)
    publication = models.CharField(max_length=150)
    isbn = models.IntegerField()
    #quantity = models.CharField(max_length=150)


    language_choice= (
        ('English','English'),
        ('Hindi','Hindi'),
        ('Urdu', 'Urdu'),

    )
    language=models.CharField(max_length=111,choices=language_choice)

    Category_choice = (
        ('programming', 'programming'),
        ('Drama', 'Drama'),
        ('Poetry', 'Poetry'),
        ('Drama', 'Drama'),
        ('Comic', 'Comic'),
        ('Novel', 'Novel'),
        ('Historical', 'Historical'),
        ('Horror', 'Horror'),
        ('Science Fiction', 'Science Fiction'),
        ('Short Story', 'Short Story'),
        ('Other Book', 'Other Book'),

    )
    category = models.CharField(max_length=111, choices=Category_choice)


    class Meta:
        db_table="book_info"


class addStudent(models.Model):
    sid = models.CharField(max_length=150)
    studentname = models.CharField(max_length=150)
    #branch = models.CharField(max_length=150)
    email = models.CharField(max_length=150)
    mobile=models.IntegerField()
    branch_choice = (
        ('Computer Science & Engineering', 'Computer Science & Engineering'),
        ('Mechanical Production', 'Mechanical Production'),
        ('Mechanical Cad', 'Mechanical Cad'),
        ('Electronic','Electronic'),
        ('Civil','Civil'),
        ('Electrical Engineering','Electrical Engineering'),
    )
    branch = models.CharField(max_length=111, choices=branch_choice)

    year_choice = (
        ('First Year', 'First Year'),
        ('Second Year', 'Second Year'),
        ('Last Year','Last Year'),
    )
    year = models.CharField(max_length=111, choices=year_choice)

    gender_choice= (
        ('Male','Male'),
        ('Female','Female'),
    )
    gender=models.CharField(max_length=111,choices=gender_choice)


    class Meta:
        db_table="student_info"



class issueBook(models.Model):
    sid = models.CharField(max_length=150)
    studentname = models.CharField(max_length=150)
    branch = models.CharField(max_length=150)
    year = models.CharField(max_length=150)

    mobile=models.IntegerField()
    bookname = models.CharField(max_length=150)
    isbn = models.IntegerField()
    authorname = models.CharField(max_length=150)
    publication = models.CharField(max_length=150)
    language = models.CharField(max_length=150)
    category = models.CharField(max_length=150)
    issuedate = models.DateField(auto_now_add=False,auto_now=False, blank=True)
    returndate = models.DateField(auto_now_add=False,auto_now=False, blank=True)


    '''language_choice = (
        ('English', 'English'),
        ('Hindi', 'Hindi'),
        ('Urdu', 'Urdu'),

    )
    language = models.CharField(max_length=111, choices=language_choice)

    Category_choice = (
        ('programming', 'programming'),
        ('Drama', 'Drama'),
        ('Poetry', 'Poetry'),
        ('Drama', 'Drama'),
        ('Comic', 'Comic'),
        ('Novel', 'Novel'),
        ('Historical', 'Historical'),
        ('Horror', 'Horror'),
        ('Science Fiction', 'Science Fiction'),
        ('Short Story', 'Short Story'),

    )
    category = models.CharField(max_length=111, choices=Category_choice)'''

    class Meta:
        db_table = "bookissue_info"




class bookDetail(models.Model):
    name=models.CharField(max_length=100)
    type=models.CharField(max_length=100)
    img=models.ImageField(upload_to='pics')
    class Meta:
        db_table="bookDetail"


class gallery(models.Model):
    title=models.CharField(max_length=100)
    g_img=models.ImageField(upload_to='gall')
    class Meta:
        db_table="gallery_img"

library/templates/about.html
{% extends 'baseIndex.html' %}

{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">

            <div class="card " style="max-width: 1540px;">
  <div class="row no-gutters">
    <div class="col-md-10">

        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/as.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/asd.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/aa.jpg' %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

    </div>
    <div class="col-md-2">
      <div class="card-body">
        <h5 class="card-title">About College</h5>
        <p class="card-text">The University of Iowa is one of the nation's premier public research universities
            with 32,535 students from 114 countries and all 50 states. Founded in 1847, it is the state's oldest
            institution of higher education
            and is located alongside the picturesque Iowa River in Iowa City.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>
       </div><!--col close-->
</div><!--row-->


</div><!-- container-->

<!----------------------------------------->


<div class="container">


</div><!--container close-->


{% endblock %}

library/templates/base.html
<!doctype html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Library Sighup</title>

    {% load static%}
<link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet" />
<link rel="stylesheet" href="{% static 'css/all.css' %}"/>
<script src="{% static 'js/jquery.js' %}" type="text/javascript" ></script>
<script src="{% static 'js/all.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}" type="text/javascript" ></script>
    <style>
    body{
background-image: url({% static 'images/1.jpg' %});

background-size: cover;
background-position: center;


}
</style>
</head>

<body>

<!---------------- nav bae start----------------------------------->
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary sticky-top">
  <a class="navbar-brand" href="#">Library</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link " href="{% url 'index'%}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sighup' %}">Signup</a>
      </li>




         <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>


           <li class="nav-item">
        <a class="nav-link" href="#">Contact</a>
      </li>
    </ul>

  </div>

</nav>



<!-------------------------------------------------------------------------------------------------->

{% block content %}





{% endblock %}






<!---------------------------------------------------------------------->


<!------------------------------------------------------>

<div class="container-fluid" style="background-color:black; margin-top:5px;">
    <div class="row">
    <div class="col-sm-12" style="width:20px;">
<br>
        <br>


    </div>


</div>
<!----------------------------->
  <div class="row">

     <div class="col-lg-2 col-md-2">
     </div>

<div class="col-lg-2 col-md-2">
    <a href="https://www.facebook.com"><i class="fab fa-facebook-square" style="color:white; font-size:50px" ></i></a>&nbsp;&nbsp;

     </div>

      <div class="col-lg-2 col-md-2">
          <a href="https://www.twitter.com"><i class="fab fa-twitter" style="color:#0099FF; font-size:50px "></i></a>&nbsp;&nbsp;

     </div>

      <div class="col-lg-2 col-md-2">
          <a href="https://www.youtube.com"><i class="fab fa-youtube" style="color:#FF0000; font-size:50px"></i></a>&nbsp;&nbsp;

     </div>

      <div class="col-lg-2 col-md-2">
          <a href="https://www.gmail.com"><i class="fas fa-mail-bulk" style="color:white; font-size:50px"></i></a> </p>

     </div>



<div class="col-lg-2 col-md-2">
     </div>
<hr style="color:white;" width="80px">
  </div><!-- row close-->
  <!--------------------------------------------------------------------------------------->
<div class="row border-1">

         <div class="col-lg-4 col-md-4">
                 <span style="color:white;">Copyright &copy; -All Rights Reserved - Our Notes - Gorakhpur(U.P).</span>

         </div>

     <div class="col-lg-4 col-md-4">



    </div>

    <div class="col-lg-4 col-md-4">
         </div>

</div>



  <div class="row">
    <div class="col-lg-5 col-md-5">
</div>
  <div class="col-lg-6 col-md-6">
  <strong>
  <a href="" style="color:#FFFFFF;"> HOME</a>&nbsp;&nbsp;
 <a href="" style="color:#FFFFFF;">SIGNUP</a>&nbsp;&nbsp;
 <a href="" style="color:#FFFFFF;">ABOUT</a>&nbsp;&nbsp;
  <a href="" style="color:#FFFFFF;">CONTACT</a>&nbsp;&nbsp;
  </strong>
  </div> <!--column close-->
   <div class="col-lg-1 col-md-1">

<a href="#top"><i class="fa fa-chevron-up" style="color:red;"></i></a>

 </div> <!--column close-->
  </div><!--row-->
<div class="row">
    <div class="col-sm-12" style="width:20px;">
<br>
        <br>


    </div>


</div>

</div> <!-- container close-->

</body>
</html>

library/templates/baseIndex.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Library Management</title>

    {% load static %}
<link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet" />
<link rel="stylesheet" href="{% static 'css/all.css' %}"/>
<script src="{% static 'js/jquery.js' %}" type="text/javascript" ></script>
<script src="{% static 'js/all.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}" type="text/javascript" ></script>

    <style type="text/css">

				#a1{
background-image: url({% static 'images/1.jpg' %});
height: 25vh;
background-size: cover;
background-position: center;


}

				#a{
background-image: url({% static 'images/home.jpg' %});
height: 100vh;
background-size: cover;
background-position: center;


}
	</style>
</head>

<body>
<div class="container-fluid">
  <div class="row bg-secondary" ><!--id='a1'-->
      <div class="col-lg-5 " >
 <h3 ALIGN="center" STYLE="color:yellow; margin-top:20px;"><i class="fas fa-university"></i> THE UNIVERSITY OF LOWA <span STYLE="color:white"> LIBRARIES</span> </h3>
      </div><!-- col---->

     <div class="col-lg-3 " >

      </div><!-- col---->


        <div class="col-lg-4 " STYLE="color:yellow; margin-top:20px;">
 <form class="form-inline my-2 my-lg-0" >
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
      </div><!-- col---->






   </div><!--row close-->



</div><!--container close-->

<!---------------- nav bae start----------------------------------->
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary sticky-top">
  <a class="navbar-brand" href="#">Library Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link " href="{% url 'index'%}">Home <span class="sr-only">(current)</span></a>
      </li>


      <li class="nav-item">
        <a class="nav-link " href="{% url 'sighup' %}">Signup</a>
      </li>




         <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>


           <li class="nav-item">
        <a class="nav-link " href="{% url 'gallery1' %}"><i class="fab fa-envira" style=""></i>Gallery</a>
      </li>

           <li class="nav-item">
        <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-sign-in-alt" style=""></i>

  Libraian Login
</button>


        </li>

    </ul>

  </div>

</nav>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color: transparent;">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLabel" style="color:white;">Login</h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color:white;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body ">
        <!-------------------->

          <form action="login" method="post">

    {% csrf_token %}
   <div class="card border-0" style="background-color: transparent;">

       <!--      <div class="card border-0">-->

        <!--<div class="card-header h1 " style="font-size:40px;color:white;" align="center">
            <img class="img" src="{% static 'images/log.png'%}" style="height: 10vh; width:15vh; ">
           Librarian Login
        </div>-->


        <div class="card-body border-0" align="center">

<div class="form-group">
  <!---  <label for="exampleInputEmail1" class="h4">User Name</label>
    <input type="text" name="userName"  class="form-control active" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter User Name">-->

<div class="input-group mb-3">

  <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1"><b>User ID</b></span>
  </div>
  <input type="text" name="userName" class="form-control" placeholder="" aria-label="Username" aria-describedby="basic-addon1">
</div>


  </div>
  <div class="form-group">
   <!-- <label for="exampleInputPassword1" class="h4">Password</label>
    <input type="password" name="password"  class="form-control" id="exampleInputPassword1" placeholder="Enter Password">-->

   <div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon2"><b>Password</b></span>
  </div><br>
  <input type="password" name="password" class="form-control" placeholder="" aria-label="Username" aria-describedby="basic-addon2">
</div>


    <small id="emailHelp" class="form-text text-muted outline-light">We'll never share your PASSWORD with anyone else.</small>



  </div>



<br>

  <button type="submit" name="btn"  class="btn btn-outline-info btn-lg ">Login</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>


        </div>


      </div>




</form>
      </div>

    </div>
  </div>
</div>
<!---------------------------------   Nav end    ----------------------------------------------->

{% block content %}





{% endblock %}







<!---------------------- Footer -------------------------------->

<div class="container-fluid" style="background-color:black; margin-top:5px;">
    <div class="row">
    <div class="col-sm-12" style="width:20px;">
<br>
        <br>


    </div>


</div>
<!----------------------------->
  <div class="row">

     <div class="col-lg-2 col-md-2">
     </div>

<div class="col-lg-2 col-md-2">
    <a href="https://www.facebook.com"><i class="fab fa-facebook-square" style="color:white; font-size:50px" ></i></a>&nbsp;&nbsp;

     </div>

      <div class="col-lg-2 col-md-2">
          <a href="https://www.twitter.com"><i class="fab fa-twitter" style="color:#0099FF; font-size:50px "></i></a>&nbsp;&nbsp;

     </div>

      <div class="col-lg-2 col-md-2">
          <a href="https://www.youtube.com"><i class="fab fa-youtube" style="color:#FF0000; font-size:50px"></i></a>&nbsp;&nbsp;

     </div>

      <div class="col-lg-2 col-md-2">
          <a href="https://www.gmail.com"><i class="fas fa-mail-bulk" style="color:white; font-size:50px"></i></a> </p>

     </div>



<div class="col-lg-2 col-md-2">
     </div>
<hr style="color:white;" width="80px">
  </div><!-- row close-->
  <!--------------------------------------------------------------------------------------->
<div class="row border-1">

         <div class="col-lg-4 col-md-4">
                 <span style="color:white;">Copyright &copy; -All Rights Reserved - Our Notes - Gorakhpur(U.P).</span>

         </div>

     <div class="col-lg-4 col-md-4">



    </div>

    <div class="col-lg-4 col-md-4">
         </div>

</div>



  <div class="row">
    <div class="col-lg-5 col-md-5">
</div>
  <div class="col-lg-6 col-md-6">
  <strong>
  <a href="{% url 'index' %}" style="color:#FF"> HOME</a>&nbsp;&nbsp;
 <a href="" style="color:#FFFFFF;">SIGNUP</a>&nbsp;&nbsp;
 <a href="{% url 'about' %}" style="color:#FFFFFF;">ABOUT</a>&nbsp;&nbsp;
  <a href="" style="color:#FFFFFF;">CONTACT</a>&nbsp;&nbsp;
  </strong>
  </div> <!--column close-->
   <div class="col-lg-1 col-md-1">

<a href="#top"><i class="fa fa-chevron-up" style="color:red;"></i></a>

 </div> <!--column close-->
  </div><!--row-->
<div class="row">
    <div class="col-sm-12" style="width:20px;">
<br>
        <br>


    </div>


</div>

</div> <!-- container close-->
</body>
</html>

library/templates/bookedit.html
{% extends 'help.html' %}
<!---------------------------------------------------------------------->

{% block content %}


<div class="container">
<div class="row">
<div class="col-sm-12">

    <div class="card">
        <div class="card-header bg-info" style="font-size:40px;" align="center">
            Update Data
        </div>


        <div class="card-body jumbotron" align="center">

<form action="/bookupdate/{{data.id}}" method="post">

    {% csrf_token %}
       <div class="row">
           <div class="col-lg-12">
               <table>
        <tr>
            <td>    Book Name
</td>
            <td>    <input type="text" name="bookname" id="id_eid" required maxlength="20" value="{{data.bookname}}">
</td>

        </tr>


           <tr>
            <td>   Author Name
</td>
            <td>    <input type="text" name="authorname" id="id_name" required maxlength="100" value="{{data.authorname}}">
</td>

        </tr>

               <tr>
            <td>   ISBN No.
</td>
            <td>    <input type="number" name="isbn" id="id_gender" required maxlength="100" value="{{data.isbn}}">
</td>

        </tr>


           <tr>
            <td>     Publication
</td>
            <td>    <input type="text" name="publication" id="id_age" required maxlength="20" value="{{data.publication}}">
</td>

        </tr>


           <tr>
            <td>     Language
</td>
            <td>    <input type="text" name="language" id="idlg" required maxlength="20" value="{{data.language}}">
</td>

        </tr>


           <tr>
            <td>     Category
</td>
            <td>    <input type="text" name="category" id="idct" required maxlength="20" value="{{data.category}}">
</td>

        </tr>




        <tr>
        <td> <br></td>
        </tr>

        <tr>
            <td colspan="2" align="center">    <input type="submit" name="btn" value="Update">
</td>

        </tr>


    </table>



           </div>

       </div>



</form>
        </div>
    </div>
</div>


   </div><!--row close-->
</div><!--container close-->






{% endblock %}

library/templates/gallery.html
{% extends 'baseIndex.html' %}

{% load static %}
{% block content %}

<div class="container">

 <div class="row">
    {% for ob1 in ob1 %}
    <div class="col-lg-4 col-md-4">

     <div class="card">

            <div class="card-body shadow">
            <img src="{{ob1.g_img.url}}" class="img img-fluid float-center" hspace="10" style="height:200px; " />
                                <hr><P CLASS="h5" align="center"> Title :- {{ ob1.title }}</P>

            </div>

      </div><br>
    </div>

    {% endfor %}




   </div><!--row close-->

</div><!--container--->

{% endblock %}

library/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Library Management</title>

    {% load static %}
<link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet" />
<link rel="stylesheet" href="{% static 'css/all.css' %}"/>
<script src="{% static 'js/jquery.js' %}" type="text/javascript" ></script>
<script src="{% static 'js/all.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}" type="text/javascript" ></script>

    <style type="text/css">



				#a{
background-image: url({% static 'images/home.jpg' %});
height: 100vh;
background-size: cover;
background-position: center;


}
	</style>
</head>

<body>

<!--------------------------------------->
<div class="container-fluid">

      <div class="row" id="a">
    <div class="col-lg-4 col-md-4" >

     </div>

             <div class="col-lg-4 col-md-4" style="margin-top:150px " >

   <!-- <div class="card border-0" style="background-color: transparent;">-->

            <div class="card border-0">

        <div class="card-header bg-info" style="font-size:40px;" align="center">
            <img class="img" src="{% static 'images/log.png'%}" style="height: 10vh; width:15vh;">
           Librarian Login
        </div>


        <div class="card-body" align="center" style="color:gray;">

<div class="form-group">
    <label for="exampleInputEmail1" class="h4">User Name</label>
    <input type="text" name="userName"  class="form-control active" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter User Name">




  </div>
  <div class="form-group">
    <label for="exampleInputPassword1" class="h4">Password</label>
    <input type="password" name="password"  class="form-control" id="exampleInputPassword1" placeholder="Enter Password">
    <small id="emailHelp" class="form-text text-muted">We'll never share your PASSWORD with anyone else.</small>



  </div>



<br>

  <button type="submit" name="btn"  class="btn btn-lg btn-block btn-primary">Login</button>


        </div>


    </div>





     </div>

             <div class="col-lg-4 col-md-4" >





     </div>




   </div><!--row close-->


</div><!--container close-->


</body>
</html>

library/templates/showsearchbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Search ho gaya
</body>
</html>

library/templates/studentedit.html
{% extends 'help.html' %}



<!---------------------------------------------------------------------->

{% block content %}


<div class="container">
<div class="row">
<div class="col-sm-12">

    <div class="card">
        <div class="card-header bg-info" style="font-size:40px;" align="center">
            Update Student Data
        </div>


        <div class="card-body jumbotron" align="center">

<form action="/studentupdate/{{data.id}}" method="post">

    {% csrf_token %}
       <div class="row">
           <div class="col-lg-12">
               <table>
        <tr>
            <td>    Student Name
</td>
            <td>    <input type="text" name="studentname" id="id_eid" required maxlength="20" value="{{data.studentname}}">
</td>

        </tr>


           <tr>
            <td>   ID
</td>
            <td>    <input type="text" name="sid" id="id_name" required maxlength="100" value="{{data.sid}}">
</td>

        </tr>

               <tr>
            <td> Email
</td>
            <td>    <input type="text" name="email" id="id_gender" required maxlength="100" value="{{data.email}}">
</td>

        </tr>


           <tr>
            <td>     Branch
</td>
            <td>    <input type="text" name="branch" id="id_age" required maxlength="20" value="{{data.branch}}">
</td>

        </tr>

                         <tr>
            <td>     Year
</td>
            <td>    <input type="text" name="year" id="id_year" required maxlength="20" value="{{data.year}}">
</td>

        </tr>

           <tr>
            <td>     Gender
</td>
            <td>    <input type="text" name="gender" id="idlg" required maxlength="6" value="{{data.gender}}">
</td>

        </tr>


           <tr>
            <td>     Mobile
</td>
            <td>    <input type="number" name="mobile" id="idct" required maxlength="10" value="{{data.mobile}}">
</td>

        </tr>


        <tr>
        <td> <br></td>
        </tr>

        <tr>
            <td colspan="2" align="center">    <input type="submit" name="btn" value="Update">
</td>

        </tr>


    </table>



           </div>

       </div>



</form>
        </div>
    </div>
</div>


   </div><!--row close-->
</div><!--container close-->






{% endblock %}